### PR TITLE
Add localization support to Float parsers

### PR DESCRIPTION
**Pull request by acosmicflamingo**
This change means I can now parse float values that do not use "." as the character for decimal separation. The test below (also included in the PR) all pass.

```swift
func testDoubleLocale() throws {
    let parser = Double.parser(
      of: Substring.UTF8View.self,
      locale: .init(identifier: "de-DE")
    )

    var input = "123 Hello"[...].utf8
    XCTAssertEqual(123, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "123, Hello"[...].utf8
    XCTAssertEqual(123, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "123,123 Hello"[...].utf8
    XCTAssertEqual(123.123, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "123,123E2 Hello"[...].utf8
    XCTAssertEqual(123.123E2, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "123,123E-2 Hello"[...].utf8
    XCTAssertEqual(123.123E-2, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "123,123E+2 Hello"[...].utf8
    XCTAssertEqual(123.123E+2, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "123E-2 Hello"[...].utf8
    XCTAssertEqual(123E-2, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "123E+2 Hello"[...].utf8
    XCTAssertEqual(123E+2, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "123E Hello"[...].utf8
    XCTAssertEqual(123, try parser.parse(&input))
    XCTAssertEqual("E Hello", String(input))

    input = "1234567890123456789012345678901234567890 Hello"[...].utf8
    XCTAssertEqual(
      1_234_567_890_123_456_846_996_462_118_072_609_669_120, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "-123 Hello"[...].utf8
    XCTAssertEqual(-123, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "+123 Hello"[...].utf8
    XCTAssertEqual(123, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "-,123 Hello"[...].utf8
    XCTAssertEqual(-0.123, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "Hello"[...].utf8
    XCTAssertThrowsError(try parser.parse(&input)) { error in
      XCTAssertEqual(
        """
        error: unexpected input
         --> input:1:1
        1 | Hello
          | ^ expected double
        """,
        "\(error)"
      )
    }
    XCTAssertEqual("Hello", String(input))

    input = "- Hello"[...].utf8
    XCTAssertThrowsError(try parser.parse(&input)) { error in
      XCTAssertEqual(
        """
        error: unexpected input
         --> input:1:1
        1 | - Hello
          | ^ expected double
        """,
        "\(error)"
      )
    }
    XCTAssertEqual(" Hello", String(input))

    input = "+ Hello"[...].utf8
    XCTAssertThrowsError(try parser.parse(&input)) { error in
      XCTAssertEqual(
        """
        error: unexpected input
         --> input:1:1
        1 | + Hello
          | ^ expected double
        """,
        "\(error)"
      )
    }
    XCTAssertEqual(" Hello", String(input))

    input = "2837,5e-2 Hello"[...].utf8
    XCTAssertEqual(28.375, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "0x1c,6 Hello"[...].utf8
    XCTAssertEqual(28.375, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "0x1,c6p4 Hello"[...].utf8
    XCTAssertEqual(28.375, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "1,23e-9999 Hello"[...].utf8
    XCTAssertEqual(0, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "-7,89e-7206 Hello"[...].utf8
    XCTAssertEqual(-0, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "1,23e17802 Hello"[...].utf8
    XCTAssertEqual(.infinity, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "-7,89e7206 Hello"[...].utf8
    XCTAssertEqual(-.infinity, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "inf Hello"[...].utf8
    XCTAssertEqual(.infinity, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "+Inf Hello"[...].utf8
    XCTAssertEqual(.infinity, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "-inF Hello"[...].utf8
    XCTAssertEqual(-.infinity, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "Infinity Hello"[...].utf8
    XCTAssertEqual(.infinity, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "+inFinity Hello"[...].utf8
    XCTAssertEqual(.infinity, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "-iNfInItY Hello"[...].utf8
    XCTAssertEqual(-.infinity, try parser.parse(&input))
    XCTAssertEqual(" Hello", String(input))

    input = "nan Hello"[...].utf8
    var output = try parser.parse(&input)
    XCTAssert(output.isNaN)
    XCTAssertEqual(" Hello", String(input))

    input = "+NaN Hello"[...].utf8
    output = try parser.parse(&input)
    XCTAssert(output.isNaN)
    XCTAssertEqual(" Hello", String(input))

    input = "-nAn Hello"[...].utf8
    output = try parser.parse(&input)
    XCTAssert(output.isNaN)
    XCTAssertEqual(" Hello", String(input))
  }
```

### CODE REVIEW

**Comment by sloik** [comment]
This is exactly what I'm missing. Why has it not been reviewed/merged yet?

**Comment by acosmicflamingo** [comment]
I haven't really pushed this PR to get merged anytime soon since it's in my forked respository that I use, and maybe it had the impression that it was a WIP. But it doesn't break anything and is ready to be merged.

Maybe now that there's another person out in the world that finds this useful, it's worth merging now? :)

**Comment by acosmicflamingo** [comment]
On Twitter, the following was stated: "The swift-parsing project does not aim to provide every possible parser that can be helpful, but instead provides a few basic ones plus all the tools needed to build your own parsers."

I initially disagreed because one can't just assume that everyone in the world uses a period for a decimal separator, but @tgrapperon pointed out to me that swift-parsing provides a parser with very similar functionality here: https://github.com/pointfreeco/swift-parsing/blob/f949081268f1f67f2cbc6e4f13a1494f6bcb0cd2/Sources/Parsing/ParserPrinters/ParseableFormatStyle.swift.

Here's how you can use it:
```diff
func testDoubleLocale() throws {
-  let parser = Double.parser(
-    of: Substring.UTF8View.self,
-    locale: .init(identifier: "de-DE")
-  )
+  let parser = Formatted(.localizedDouble(locale: "de-DE"))
 
-  var input = "123 Hello"[...].utf8
+  var input = "123 Hello"[...]
   XCTAssertEqual(123, try parser.parse(&input))
   XCTAssertEqual(" Hello", String(input))

  input = "123,123 Hello"[...]
  XCTAssertEqual(123.123, try parser.parse(&input))
  XCTAssertEqual(" Hello", String(input))

  input = "123,123E2 Hello"[...]
  XCTAssertEqual(123.123E2, try parser.parse(&input))
  XCTAssertEqual(" Hello", String(input))
}
```

Now that I'm aware of its existence, it makes much more sense why adding this functionality to Float.parser seems inappropriate, so I'll close this PR.

**Comment by acosmicflamingo** [comment]
Actually, I found an even better solution that does 100% of what I was using the changes in this PR for. I didn't realize that `Decimal.FormatStyle` was so customizable; I thought that I either use `Formatted(.number)`, or `Formatted(.localizedDouble(locale: "de-DE"))`, but it turns out that it's possible to configure a formatStyle instance the same way a SwiftUI View can have a chain of functions that mutate the object:
```swift
let formatStyle = Decimal.FormatStyle.number
  .locale(.init(identifier: "en-US"))
  .decimalSeparator(strategy: .automatic)
  .grouping(.never))
let parser = Formatted(formatStyle)
```
The very important key that makes this possible is the 'grouping(.never)' function. It is what ensures that if you pass the parser "1.2.3.4.5", the "1.2" would be extracted, and the remainder would be ".3.4.5" instead of extracting nil and leaving the input intact. Woohoo!!!!!!!!!!!

Disclaimer: this is only possible when your minimum deployment target is iOS 16.0. This isn't a problem with me, which is why I'm a happy camper :)

**Pull request closed without merging**
